# - Try to find dbghelp.dll
# Once done, this will define
#
# DBGHELP_FOUND - system has dbghelp.dll
# DBGHELP_LIBRARY - link these to use dbghelp.dll

SET(DBGHELP_LIBRARY "${CMAKE_CURRENT_SOURCE_DIR}/bin/dbghelp.dll")

MESSAGE(STATUS "DBGHELP: ${DBGHELP_LIBRARY}")
IF(DBGHELP_LIBRARY)
	SET( DBGHELP_FOUND TRUE )	
ENDIF(DBGHELP_LIBRARY)
IF(DBGHELP_FOUND)
	IF(NOT DBGHELP_FIND_QUIETLY)
	MESSAGE(STATUS "Found DBGHELP: ${DBGHELP_LIBRARY}")
	ENDIF(NOT DBGHELP_FIND_QUIETLY)
ELSE(DBGHELP_FOUND)
	IF(DBGHELP_FIND_REQUIRED)
	MESSAGE(FATAL_ERROR "Could not find dbghelp.dll")
	ENDIF(DBGHELP_FIND_REQUIRED)
ENDIF(DBGHELP_FOUND)